### ISSUE TITLE
友链交换

### ISSUE THREAD

**Issue by Shtraiy** [Subilan/subilan.github.io#15]
网站名称：Nocturne
网站介绍：Ivory Tower
网站代表色：#009999
网站地址：wynio.online
头像：https://i.328888.xyz/2023/01/17/2LG3w.png

**Comment by Subilan** [comment]
加了～

**Comment by Shtraiy** [comment]
okok

Yuenleung So ***@***.***> 于2023年1月21日周六 14:57写道：

**Comment by Shtraiy** [comment]
su老师新年快乐，最新域名更新为wynio.pw，头像url为https://www.wynio.pw/css/logo.png

**Comment by Subilan** [comment]
收到🫡，马上更新
