### ISSUE TITLE
友情链接可以进行更新

### ISSUE THREAD

**Issue by JimmyRice** [Subilan/subilan.github.io#26]
嗨！好久不见，我是 [Jimmy0w0](https://jimmy0w0.me) 的站长

跟贵站交换的友链 [Jimmy0w0 moe](https://moe.jimmy0w0.me) 在去年的九月已经停止更新了，取代它的将是新的 [Jimmy0w0](https://jimmy0w0.me) 网站，并且目前已将贵站的链接放入[友情链接](https://jimmy0w0.me/friends/)的页面当中

不过，新的网站文章过少并且还在不断完善文章和功能，所以不太符合贵站的交换需求。因此更新与否就交由 su 老师考虑啦

祝好 XD，
Jimmy

**Comment by Subilan** [comment]
Your site is fxxking awesome! 那必须得加啊（震声）。

[链接已经修改](https://github.com/Subilan/Blog/commit/7155e9803cd08fdaabde56bdf2f9ee14c71e88e5)。如果其它地方也需要修改的话，可以再和我说～

祝好！

**Comment by JimmyRice** [comment]
OMG 谢谢 fking awesome 的夸奖，也欢迎 su 老师常来串门。

那我先关闭这个 issue 啦

Good luck!
