### ISSUE TITLE
友链交换申请

### ISSUE THREAD

**Issue by Mashirl** [Subilan/subilan.github.io#3]
网站名称：Mashirl's Blog

网站介绍：予 世界温柔以待 惟愿 时光静好

网站代表色：#FFAEB9

网站地址：https://www.mashirl.cn

头像：https://resource.mashirl.cn/images/avatar.jpg

**Comment by Subilan** [comment]
哦天哪我居然现在才看到，实在抱歉，已添加~

**Comment by Mashirl** [comment]
> 哦天哪我居然现在才看到，实在抱歉，已添加~

好的 我这边也添加上您了。
