### ISSUE TITLE
友链申请

### ISSUE THREAD

**Issue by Fidelxyz** [Subilan/subilan.github.io#4]
网站名称：Fidel's Lab
网站介绍：玄云Fidel's Blog
网站地址：https://fidel.js.org
头像（圆）：https://gravatar.loli.net/avatar/bccd181c71d3a08f6c182f3f48164545

似乎之前您在我这加过友链～今天迁移回GitHub Pages才发现您的Blog更新了，友链也重新申请一下qwq

**Comment by Subilan** [comment]
您好~友链已经添加了~

不过有两点问题
- 介绍建议写一些个人简介、博客简介、座右铭之类的~~ 比如「隐约雷鸣，阴霾天空」
- 由于我对友链页面的设计，是需要为你的链接加上背景颜色（HEX）或者背景图片的~~但是您好像没有提供，所以我暂时设置成黑色了（`#000`）。如果您想要变更，可以继续给我留言！

**Comment by Fidelxyz** [comment]
重新把banner做了一遍，那就加个背景图片吧~
图片链接：`https://sm.ms/image/Sa7dWDtVMivUnoQ`

描述的话，可以写这一句：不乱于心，不困于情。不畏将来，不念过往。
（不过好像有~~亿~~点长QwQ

**Comment by Subilan** [comment]
已更新～
