### ISSUE TITLE
交换友链 阿里嘎多

### ISSUE THREAD

**Issue by hkyang233** [Subilan/subilan.github.io#6]
网站名称：Yang's Blog
网站介绍：迷失的人迷失了，相逢的人会相逢
网站地址：https://yang233.top
头像（圆/方皆可）：方

**Comment by Subilan** [comment]
你好，抱歉这么久没有回复，友链已添加~

头像的那一栏「圆/方皆可」指的是头像本体既可以是圆的也可以是方的，实际需要提供的是图片的链接。我访问了你的博客，找到了头像的链接 https://yangblog.top/img/logo.jpg，如果这不正确，欢迎回复告诉我。

以及需要提供一下自己网站的代表色（HEX 或者 RGB），我暂时设置成了白色。

**Comment by hkyang233** [comment]
> 你好，抱歉这么久没有回复，友链已添加~
> 
> 头像的那一栏「圆/方皆可」指的是头像本体既可以是圆的也可以是方的，实际需要提供的是图片的链接。我访问了你的博客，找到了头像的链接 <https://yangblog.top/img/logo.jpg>，如果这不正确，欢迎回复告诉我。
> 
> 以及需要提供一下自己网站的代表色（HEX 或者 RGB），我暂时设置成了白色。

没事，谢谢大佬了~~

**Comment by Subilan** [comment]
你好，请问这边无法获取到你的头像，访问网站是这样的结果
![image](https://user-images.githubusercontent.com/36447840/80549437-d7447b80-89ef-11ea-8515-f98d78e26a5e.png)

是我这边的问题吗？

**Comment by hkyang233** [comment]
> 你好，请问这边无法获取到你的头像，访问网站是这样的结果
> ![image](https://user-images.githubusercontent.com/36447840/80549437-d7447b80-89ef-11ea-8515-f98d78e26a5e.png)
> 
> 是我这边的问题吗？

阿勒，试试yang233.top/img/logo.jpg

**Comment by Subilan** [comment]
OK，我发现是代理的问题😂

一切都是正常的，打扰了~
