### ISSUE TITLE
友链申请

### ISSUE THREAD

**Issue by SimonRiley-343** [Subilan/subilan.github.io#8]
网站名称：WindSpirit IT
网站介绍：跟随互联网发展的每一步
网站代表色：#262626
网站地址：https://www.leviatan.cn/
头像：[Url](https://www.leviatan.cn/chevereto/images/2020/02/26/01e87e28661f72ed13f55a444a49fdcc.md.png)

**Comment by Subilan** [comment]
OHHHHHHHHHHHHHHHHH

已添加~
